---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: localhost
  ansible_verbose: true
  ansible_verbosity: 4

platforms:
  - name: centos-7.3
    driver_config:
      privileged: true
      run_command: /sbin/init; sleep 5

suites:
  - name: default
